# src/utils/config.py (Versión Depurada)

CAMERA_URL = "http://192.168.100.35:8080/video"
RECONNECT_DELAY_SECONDS = 2
DATASET_DIR = "data/dataset"
MAX_PHOTOS_PER_PERSON = 30
BLUR_THRESHOLD = 70.0

# --- CONFIGURACIÓN DEL MODELO VECTORIAL ---
# Ruta única y definitiva del modelo
MODEL_PATH: str = "data/models/encodings.pkl"

# --- CONFIGURACIÓN INSIGHTFACE (SCRFD + ARCFACE) ---
INSIGHTFACE_MODEL_PACK = "buffalo_l"
INSIGHTFACE_DET_THRESH = 0.5
INSIGHTFACE_INPUT_SIZE = (640, 640)
INSIGHTFACE_EMBEDDING_SIZE = 512
INSIGHTFACE_REC_THRESH = 0.45

# --- CONFIGURACIÓN DEL TRACKER (BYTETRACK) ---
TRACKER_BUFFER = 30
TRACKER_MATCH_THRESH = 0.8
