// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtX7uKiGBcJKANRZ4KLW3Tvge2NgDsmoU',
    appId: '1:939488062488:web:fa939b5ee7535a1089a76d',
    messagingSenderId: '939488062488',
    projectId: 'motor-c7e0d',
    authDomain: 'motor-c7e0d.firebaseapp.com',
    databaseURL: 'https://motor-c7e0d-default-rtdb.firebaseio.com',
    storageBucket: 'motor-c7e0d.firebasestorage.app',
    measurementId: 'G-VYYSKWPDCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWlnITnkAFluSG6BUhz4aMZmLXwoMs-U',
    appId: '1:939488062488:android:a9e4d703592d5caf89a76d',
    messagingSenderId: '939488062488',
    projectId: 'motor-c7e0d',
    databaseURL: 'https://motor-c7e0d-default-rtdb.firebaseio.com',
    storageBucket: 'motor-c7e0d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3432wtsDzofKny8YelsQ48ZKi1zC1V4c',
    appId: '1:939488062488:ios:ee6ee6e6d407bf8389a76d',
    messagingSenderId: '939488062488',
    projectId: 'motor-c7e0d',
    databaseURL: 'https://motor-c7e0d-default-rtdb.firebaseio.com',
    storageBucket: 'motor-c7e0d.firebasestorage.app',
    iosBundleId: 'com.example.frontendSica',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3432wtsDzofKny8YelsQ48ZKi1zC1V4c',
    appId: '1:939488062488:ios:ee6ee6e6d407bf8389a76d',
    messagingSenderId: '939488062488',
    projectId: 'motor-c7e0d',
    databaseURL: 'https://motor-c7e0d-default-rtdb.firebaseio.com',
    storageBucket: 'motor-c7e0d.firebasestorage.app',
    iosBundleId: 'com.example.frontendSica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtX7uKiGBcJKANRZ4KLW3Tvge2NgDsmoU',
    appId: '1:939488062488:web:a8b5c6e533b6b7bf89a76d',
    messagingSenderId: '939488062488',
    projectId: 'motor-c7e0d',
    authDomain: 'motor-c7e0d.firebaseapp.com',
    databaseURL: 'https://motor-c7e0d-default-rtdb.firebaseio.com',
    storageBucket: 'motor-c7e0d.firebasestorage.app',
    measurementId: 'G-TQDSW3FS90',
  );
}
