// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtSoYtmQGABLfwBGcA-ln9mWB_i6_K-RU',
    appId: '1:577669516511:web:b46f09fb7a36bac2a7ed6a',
    messagingSenderId: '577669516511',
    projectId: 'sica-app-colegio',
    authDomain: 'sica-app-colegio.firebaseapp.com',
    storageBucket: 'sica-app-colegio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDPPd6aQrpjzPnFebQwC4MpTHMQgY9fKs',
    appId: '1:577669516511:android:6dd5fa0cf855a446a7ed6a',
    messagingSenderId: '577669516511',
    projectId: 'sica-app-colegio',
    storageBucket: 'sica-app-colegio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBamsj1LbGpls0aITqn5zci0rRrOe5W0eI',
    appId: '1:577669516511:ios:5d09039cd8e5872ea7ed6a',
    messagingSenderId: '577669516511',
    projectId: 'sica-app-colegio',
    storageBucket: 'sica-app-colegio.firebasestorage.app',
    iosBundleId: 'com.example.frontendSica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBamsj1LbGpls0aITqn5zci0rRrOe5W0eI',
    appId: '1:577669516511:ios:5d09039cd8e5872ea7ed6a',
    messagingSenderId: '577669516511',
    projectId: 'sica-app-colegio',
    storageBucket: 'sica-app-colegio.firebasestorage.app',
    iosBundleId: 'com.example.frontendSica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtSoYtmQGABLfwBGcA-ln9mWB_i6_K-RU',
    appId: '1:577669516511:web:ec99e91879439147a7ed6a',
    messagingSenderId: '577669516511',
    projectId: 'sica-app-colegio',
    authDomain: 'sica-app-colegio.firebaseapp.com',
    storageBucket: 'sica-app-colegio.firebasestorage.app',
  );
}
